# Generated by Django 5.0.2 on 2024-02-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_text',
            field=models.CharField(default='this is the string', max_length=200),
            preserve_default=False,
        ),
    ]
